adoa/adoa/urls.py
from django.conf.urls import *
from adoa.views import *
from django.conf.urls import include, url
	


urlpatterns = [

    url(r'^$', index),
    url(r'^index/', index, name='index'),
    url(r'^ayuda/', ayuda, name='ayuda'),
    url(r'^queEsOA/', queEsOA, name='queEsOA'),
    url(r'^queEsPatron/', queEsPatron, name='queEsPatron'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^inicioOA/', inicioOA, name = 'inicioOA'),
    url(r'^contenidosOA/', contenidosOA, name = 'contenidosOA'),
    url(r'^guardarcontenidosOA/', guardarcontenidosOA, name = 'guardarcontenidosOA'),
    url(r'^guardarActividadesOA/', guardarActividadesOA, name = 'guardarActividadesOA'),    
    url(r'^patrones/', patrones, name = 'patrones'),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),



]

adoa/urls.py
from django.conf.urls import include, url
from adoa.views import *

# from . import views

urlpatterns = [
    # url(r'^$', index, name='index'),
    url(r'^$', Index.as_view()),
    url(r'^index/', Index.as_view(), name='index'),


    url(r'^queEsOA/', QueEsOA.as_view(), name='queEsOA'),
    url(r'^queEsPatron/', QueEsPatron.as_view(), name='queEsPatron'),
    url(r'^ayuda/', Ayuda.as_view(), name='ayuda'),
    url(r'^patrones/', PatronesView.as_view(), name = 'patrones'),

    url(r'^oa/$', ObjetoAprendizajeList.as_view(), name='list'),
    url(r'^oa/(?P<pk>\d+)$', ObjetoAprendizajeDetail.as_view(), name='detail'),
    url(r'^oa/nuevo$', ObjetoAprendizajeCreate.as_view(), name='new'),
    url(r'^oa/editar/(?P<pk>\d+)$', ObjetoAprendizajeUpdate.as_view(), name='edit'),
    url(r'^oa/borrar/(?P<pk>\d+)$', ObjetoAprendizajeDelete.as_view(), name='delete'),
    url(r'^oa/patron$', ContenidoView.as_view(), name='patron'),
    url(r'^oa/contenido$', ContenidoCreate.as_view(), name='contenido'),
    url(r'^oa/elementoasociacion$', ElementoAsociacionCreate.as_view(), name='elementoasociacion'),
    url(r'^oa/elementovof$', ElementoVoFCreate.as_view(), name='elementovof'),
    url(r'^oa/elementoidentificacion$', ElementoIdentificacionCreate.as_view(), name='elementoidentificacion'),
    url(r'^oa/elementoordenamiento$', ElementoOrdenamientoCreate.as_view(), name='elementoordenamiento'),
    url(r'^oa/elementoopcionmultiple$', ElementoOpcionMultipleCreate.as_view(), name='elementoopcionmultiple'),
]

proyecto/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^', include('adoa.urls', namespace='adoa')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

adoa/adoa/models.py
from django.db import models
from django.contrib import admin
# from tinymce.models import HTMLField
from django.contrib.auth.models import *
from ckeditor.fields import RichTextField
# Create your models here.



class Patron(models.Model):
    titulo = models.CharField(max_length=30)
    descripcion = RichTextField()
    problemas = RichTextField()
    solucion = RichTextField()
    def __unicode__(self):
       return self.titulo


class ContenidoPatron(models.Model):
    orden = models.IntegerField()
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length = 200)
    patron = models.ForeignKey(Patron)
    def _get_titulo(self):
        return self.titulo
    def _get_descripcion(self):
        return self.descripcion
    def _get_orden(self):
        return self.orden

    def __unicode__(self):
       return self.titulo


class ObjetoAprendizaje(models.Model):
    titulo=models.CharField(max_length=30)
    descripcion= RichTextField()
    patron = models.ForeignKey(Patron)
    user = models.ForeignKey(User)
    def setearContenidos(self):
        li=[]
        for contenidoPatron in ContenidoPatron.objects.all():
            if contenidoPatron.patron == self.patron:
                contenido = Contenido(titulo = contenidoPatron._get_titulo(), descripcion = contenidoPatron._get_descripcion(), orden = contenidoPatron._get_orden(),objetoAprendizaje = self)
                li.append(contenido)
        return li
    def setearActividad(self):
        li=[]
        vof=VerdaderoFalso(titulo = "VerdaderoFalso", descripcion = "aoifjoiajs", enunGeneral = "oiafsoij", objetoAprendizaje= self)
        li.append(vof)
        return li
    def __unicode__(self):
       return self.titulo


class Contenido(models.Model):
    orden = models.IntegerField()
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length = 200)
    contenido = RichTextField()
    objetoAprendizaje = models.ForeignKey(ObjetoAprendizaje)
    def __unicode__(self):
       return self.titulo

#--------------------------------------------------------------------------

class Actividad(models.Model):
    titulo = models.CharField(max_length=30)
    objetoAprendizaje = models.ForeignKey(ObjetoAprendizaje)
    def __unicode__(self):
       return self.titulo

#--------------------------------------------------------------------------

class VerdaderoFalso(Actividad):
    enunGeneral =  models.CharField(max_length = 30)
    descripcion = RichTextField()


class ElementoVoF(models.Model):
    enunciado = models.CharField(max_length = 30)
    verdad = models.BooleanField()
    VoF = models.ForeignKey(VerdaderoFalso)

#--------------------------------------------------------------------------

class Ordenamiento(Actividad):
    enunGeneral =  models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoOrdenamiento(models.Model):
    enunciado = models.CharField(max_length = 30)
    orden = models.IntegerField()
    ordenamiento = models.ForeignKey(Ordenamiento)

#--------------------------------------------------------------------------


class OpcionMultiple(Actividad):
    enunGeneral = models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoOpcionMultiple(models.Model):
    enunciado = models.CharField(max_length = 30)
    correcta = models.CharField(max_length = 30)
    incorrecta1 = models.CharField(max_length = 30)
    incorrecta2 = models.CharField(max_length = 30)
    incorrecta3 = models.CharField(max_length = 30)
    multiple = models.ForeignKey(OpcionMultiple)

#-------------------------------------------------------------

class Identificacion(Actividad):
    enunGeneral = models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoIdentificacion(models.Model):
    enunciado = models.CharField(max_length = 30)
    correcto = models.BooleanField()
    identificacion = models.ForeignKey(Identificacion)

#----------------------------------------------------------

class Asociacion(Actividad):
    enunGeneral = models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoAsosiacion(models.Model):
    enunciado = models.CharField(max_length = 30)
    imagen = models.ImageField()
    asociacion = models.ForeignKey(Asociacion)

adoa/forms.py
from django import forms
from django.forms import ModelForm, inlineformset_factory, BaseInlineFormSet, formset_factory
from django.forms.formsets import BaseFormSet
from models import *
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from ckeditor.widgets import CKEditorWidget
from crispy_forms.bootstrap import *
from djangoformsetjs.utils import formset_media_js
import pdb

class ObjetoAprendizajeForm(forms.ModelForm):
    class Meta:
        model = ObjetoAprendizaje
        fields = ['titulo','patron','descripcion']
    titulo = forms.CharField(max_length = 30)
    descripcion = forms.CharField(widget=CKEditorWidget())
    patron = forms.ModelChoiceField(queryset=Patron.objects.all())
    def __init__(self, *args, **kwargs):
        super(ObjetoAprendizajeForm, self).__init__(*args, **kwargs)
        self.helper= FormHelper()
        self.helper.layout = Layout(
            Div(
                Field('patron'),
                HTML("<a href= '{% url 'adoa:patrones' %}''>Que patron elegir? </a>"),
                Field('titulo'),
                Field('descripcion'),
                # HTML('<input type="submit" class="btn btn-primary" value="Continuar &rarr;">'),
        css_class='row-fluid'),
        )
#--------------------------------------------------------------------------
class PatronForm(ModelForm):
    class Meta:
        model = Patron
        fields = ['titulo', 'descripcion', 'problemas', 'solucion']
# #--------------------------------------------------------------------------
class ContenidoForm(forms.ModelForm):
    class Meta:
        model = Contenido
        fields = ['orden','titulo','descripcion','contenido']
    orden = forms.IntegerField()
    titulo = forms.CharField(max_length=100)
    descripcion = forms.CharField(max_length=300)
    contenido = forms.CharField(widget=CKEditorWidget())
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Field('orden',type='hidden'),
                Field('titulo'),
                Field('descripcion'),
                Field('contenido'),
                css_class='row-fluid'),
            )
        super(ContenidoForm, self).__init__(*args, **kwargs)
#--------------------------------------------------------------------------

class ElementoVoFForm(forms.ModelForm):
    class Meta:
        model = ElementoVoF
        fields = ['enunciado','verdad']

class ElementoAsociacionForm(forms.ModelForm):
    class Meta:
        model = ElementoAsociacion
        fields = ['enunciado','imagen']

class ElementoIdentificacionForm(forms.ModelForm):
    class Meta:
        model = ElementoIdentificacion
        fields = ['enunciado','correcto']

class ElementoOpcionMultipleForm(forms.ModelForm):
    class Meta:
        model = ElementoOpcionMultiple
        fields = ['enunciado','correcta','incorrecta1','incorrecta2','incorrecta3']

class ElementoOrdenamientoForm(forms.ModelForm):
    class Meta:
        model = ElementoOrdenamiento
        fields = ['enunciado','orden']
#--------------------------------------------------------------------------

class UserLoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

#--------------------------------------------------------------------------

adoa/adoa/views.py
from django.template import loader, Context
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from adoa.models import *
from django.shortcuts import render_to_response
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from forms import *
from django.contrib.sessions import *
from django.contrib.admin import *
from django.forms import formsets
from django.forms import modelformset_factory
from django.forms import formset_factory






# Create your views here.
def archive(request):
    patrones = Patron.objects.all()
    mi_template = loader.get_template("archive.html")
    mi_contexto = Context({'patrones': patrones})
    return HttpResponse(mi_template.render(mi_contexto))


def ayuda(request):
    title = 'Sign Up Now'
    context = {
        "title": title,
     }
    return render (request,"ayuda.html",context)


def queEsOA(request):
    title = 'Sign Up Now'
    context = {
        "title": title,
     }
    return render (request,"queEsOA.html",context)
    


def queEsPatron(request):
    title = 'Sign Up Now'
    context = {
        "title": title,
     }
    return render (request,"queEsPatron.html",context)



def index(request):
    title = 'Sign Up Now'
    form = UserLoginForm(request.POST or None)
    context = {
        "title": title,
        "form": form
    }
    if form.is_valid():
        instance = form.save(commit=False)
        username = form.cleaned_data.get("username")
        if not username:
            username = "New username"
        instance.username = username
        # if not instance.full_name:
        #    instance.full_name = "Justin"
        instance.save()
        context = {
            "title": "Thank you"
        }
    # if request.user.is_authenticated() and request.user.is_staff:
    #     queryset = User.objects.all()
    #     context = {
    #         "queryset": queryset
    #     }
    return render(request, "index.html", context)


def inicioOA(request):
    title = 'Inicio OA'
    form = ObjetoAprendizajeForm(request.POST or None)
    context = {
        "title": title,
        "form": form
    }


    if form.is_valid():
       
        titulo1 = form.cleaned_data.get("titulo")
        descripcion1 = form.cleaned_data.get("descripcion")
        patron1 = form.cleaned_data.get("patron")
        user_request = request.user 
        

        user = User.objects.get(username = user_request)
        oa = ObjetoAprendizaje(titulo = titulo1, descripcion = descripcion1, patron = patron1, user = user)
        
        if not ObjetoAprendizaje.objects.filter(pk=oa.pk).exists():
            oa.save()
            for contenido in oa.setearContenidos():
                contenido.save()
            for vof in oa.setearActividad():
                print vof
                vof.save()
        request.session["oa_pk"] = oa.pk

        context = {
            "title": "Thank you",
             "oa": oa
        }

        return contenidosOA(request)
    else:
        return render(request, "inicioOA.html", context)
    
def contenidosOA(request):
    
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])
    title = 'Contenidos OA'
    ContenidoFormSet =  inlineformset_factory(ObjetoAprendizaje,Contenido,fields=('orden','titulo','descripcion','contenido','objetoAprendizaje'), extra = 0)
    context = { 
            "title": title,
        }

    formset = ContenidoFormSet(instance = oa,)
    context = { 
        "title": title,
        "formset": formset,
    }
    return render(request,"contenidosOA.html", context)


def guardarcontenidosOA(request):
    ContenidoFormSet =  inlineformset_factory(ObjetoAprendizaje,Contenido,fields=('orden','titulo','descripcion','contenido','objetoAprendizaje'), extra = 0)
    
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])
        
    formset = ContenidoFormSet(request.POST, instance = oa)

    title = 'Guardar contenidos OA'
    context = { 
            "title": title,
        }
    for form in formset:
        print form.as_p

    print "1111"
    print formset.errors
    
    if formset.is_valid():
        print "22222"
        for f_form in formset:
            if f_form.is_valid():
                print "3333"
                orden =  f_form.cleaned_data.get("orden")
                titulo = f_form.cleaned_data.get("titulo")
                descripcion = f_form.cleaned_data.get("descripcion")
                content = f_form.cleaned_data.get("contenido")
                objetoAprendizaje = f_form.cleaned_data.get("objetoAprendizaje")
                contenido = Contenido(orden = orden, titulo = titulo, descripcion = descripcion,contenido = content, objetoAprendizaje = objetoAprendizaje)
                contenido.save()
                print "4444"
            return actividades(request)
    else:
        return ayuda(request)



def patrones(request):
    title = 'Patrones'
    patrones = Patron.objects.all()
    form = PatronForm()
    context = {
        "title":title,
        "form": form,
        "patrones": patrones
    }
    return render(request,"patrones.html",context)

def actividades(request):
    title = 'actividades'
    ActividadFormset = inlineformset_factory(ObjetoAprendizaje,VerdaderoFalso,fields=('titulo','enunGeneral','descripcion','objetoAprendizaje'), extra = 0)
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])
    formset = ActividadFormset(instance = oa)

    context = { 
        "title": title,
        "formset": formset,
    }
    return render(request,"actividades.html", context)


def guardarActividadesOA(request):
    ActividadFormset = inlineformset_factory(ObjetoAprendizaje,VerdaderoFalso,fields=('titulo','enunGeneral','descripcion','objetoAprendizaje'), extra = 0)
    
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])        
    formset = ActividadFormSet(request.POST, instance = oa)

    title = 'Guardar Actividades OA'
    context = { 
            "title": title,
        }
    for form in formset:
        print form.as_p

    print "1111"
    print formset.errors
    
    if formset.is_valid():
        print "22222"
        for f_form in formset:
            if f_form.is_valid():
                print "3333"
                titulo = f_form.cleaned_data.get("titulo")
                descripcion = f_form.cleaned_data.get("descripcion")
                enunGeneral = f_form.cleaned_data.get("enunGeneral")
                objetoAprendizaje = f_form.cleaned_data.get("objetoAprendizaje")
                contenido = Contenido(titulo = titulo, descripcion = descripcion, enunGeneral = enunGeneral, objetoAprendizaje = objetoAprendizaje)
                contenido.save()
        return index(request)
    else:
        return ayuda(request)

adoa/templates/_oa_details.html
<h1>Titulo</h1>
{{ oa.titulo }}
<h1>Descripcion</h1>
{{ oa.Descripcion }}
<h1>Patron</h1>
{{ oa.patron }}
<h1>contenidos</h1>
{% for contenido in contenidos %}
  <h2>Orden</h2>
  {{ contenido.orden }}
  <h2>Titulo</h2>
  {{ contenido.titulo }}
  <h2>Descripcion</h2>
  {{ contenido.descripcion }}
  <h2>Contenido</h2>
  {{ contenido.contenido }}}
{% endfor %}
<h1>Actividades</h1>
{% for actividad in actividades %}
  <h2>Titulo</h2>
  {{ actividad.enunciado }}
  <h2>Tipo</h2>
  {{ actividad.tipo }}
{% endfor %}

adoa/templates/actividades.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
<!DOCTYPE html>
{% crispy form %}



{% block head_title %}Contenidos del OA | {{ block.super }}{% endblock %}
{% block style %}

.center {
    margin: auto;
    width: 10%;
    padding: 10px;
}

{% endblock %}

{% block jumbotron %}


{% endblock %}

{% block content %}

{% csrf_token %}

<table>





          <form id="myForm" method="POST" action="{%url 'adoa:guardarcontenidosOA'%}">
            {% csrf_token %}
              {{ formset.management_form }}
              <table border="0" cellpadding="0" cellspacing="0">
                  <tbody>
                      {% for form in formset.forms %}
                      {% crispy form %}


                        {% for hidden in form.hidden_fields %}
                          {{ hidden }}
                        {% endfor %}
                      </tr>

                      {% endfor %}
                  </tbody>
              </table>

              <div class='well'><center><button type='submit' class='btn btn-success' >Guardar y contiunar</button></center></div>
          </form>



      </table>
    {% endblock %}

adoa/templates/archive1.html
{% for oa in oas %}
<h2>{{oa.titulo}}</h2>
<p>{{oa.descripcion}}</p>
{% endfor%}

adoa/templates/contenidosOA.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<!-- {% crispy form %} -->



{% block head_title %}Contenidos del OA | {{ block.super }}{% endblock %}
{% block style %}

.center {
    margin: auto;
    width: 10%;
    padding: 10px;
}

{% endblock %}

{% block jumbotron %}


{% endblock %}

{% block content %}

  {% csrf_token %}
  {% for form in formset %}
    {% crispy form  %}
  {% endfor %}
{% endblock %}

adoa/templates/head_css.html
{% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    
    
    <link rel="stylesheet" href= "{% static 'css/bootstrap.css' %}">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
 <!--    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'css/custom.css' %}" rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

adoa/templates/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
<!DOCTYPE html>
{% block head_title %}Index | {{ block.super }}{% endblock %}


<!--  SECTION-1 -->


{% block jumbotron %}
<div class="container">
  <div class="jumbotron text-center">
      <div class="row">
        <div class="col-xs12"><img src="{% static 'img/index/nuevoindex1.png' %}" class="img-responsive" alt="Placeholder image"> </div>
      </div>
    </div>
  </div>

{% endblock %}
{% block content %}
          <br></br>
   </center>
  </div>
  <div class="container ">
    <div class="row">
      <div class="col-lg-4 col-sm-12 text-center"> <a href="{% url 'adoa:queEsOA' %}"> <img class="img-circle" alt="140x140" style="width: 140px; height: 140px;" src="{% static 'img/index/redes.jpg' %}" data-holder-rendered="true">
        <h3>¿Qué es un Objeto de Aprendizaje?</h3>
        </a>
        <p>Se resume como una colección de contenidos, ejercicios, y evaluaciones que son combinados sobre la base de un objetivo de aprendizaje simple.<br> <a href="{% url 'adoa:queEsOA' %}"> Ver más.</a></br></p>
      </div>
      <div class="col-lg-4 col-sm-12 text-center"> <a href="{% url 'adoa:queEsPatron' %}"> <img class="img-circle" alt="140x140" style="width: 140px; height: 140px;" src="{% static 'img/index/cerebro1.png' %}" data-holder-rendered="true">
        <h3>¿Qué es un Patrón Pedagógico?</h3>&nbsp;
      </a>
        <p>Los Patrones Pedagógicos formalizan el conocimiento experto de la enseñanza y el aprendizaje, fácilmente comunicable a aquellos que necesitan ese conocimiento. <a href="{% url 'adoa:queEsPatron' %}"> Ver más.</a></p>
      </div>
      <div class="col-lg-4 col-sm-12 text-center"><a href="{% url 'adoa:ayuda' %}"><img class="img-circle" alt="140x140" style="width: 140px; height: 140px;" src="{% static 'img/index/pregunta.jpg' %}" data-holder-rendered="true">
        <h3>¿Porqué nuestro programa lo ayudará?</h3>
      </a>
        <p>Información sobre las utilidades del programa y como aprovechar al maximo sus utilidades. <br><a href="{% url 'adoa:ayuda' %}">Ver más.</a></br></p>
      </div>
</div>
<!-- /container -->



  <!-- / CONTAINER-->
</section>
<div class="well">
  <center><button type="button" class="btn btn-success" onclick="location.href='{% url 'adoa:new' %}'" >Crear OA</button></center>
</div>

{% endblock %}

adoa/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
	<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
	<!--<script src="{% static 'js/jquery.formset.js' %}"></script>
	<script src="{% static 'js/jquery.formset.min.js' %}"></script> -->

adoa/templates/login.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>Login</h1>
<form method="post" action=".">
  {% csrf_token %}
  {{ form|crispy }}

  <input class='btn btn-block btn-primary' type="submit" value="{% trans 'Submit' %}" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>
</div>

</div>
<hr/>
<div class='row'>
<div class='col-sm-6 col-sm-offset-3 text-align-center'>
<p>{% trans "Forgot password" %}? <a href="{% url 'auth_password_reset' %}">{% trans "Reset it" %}</a>!</p>
<p>{% trans "Not member" %}? <a href="{% url 'registration_register' %}">{% trans "Register" %}</a>!</p>
</div>
</div>

{% endblock %}

adoa/templates/navbar.html
   {% load staticfiles %}

   <!-- Static navbar -->

    <nav class="navbar navbar-default ">

      <div class="container">


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div id="navbar" class="navbar-collapse collapse">
<div><a class="navbar-brand" href="{% url 'adoa:index' %}"><img src="{% static 'img/index/logov3.8.png' %}"  WIDTH=60, HEIGTH=60  /></a></div>
          <ul class="nav navbar-nav">

            <li><a href="{% url 'adoa:index' %}">Home</a></li>
            <li><a href="">¿Quiénes somos?</a></li>
            <li><a href="">Contacto</a></li>
          </ul>


          <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'adoa:index' %}">Bienvenido {{ user.get_username }}</a></li>
            <li><a href="{% url 'auth_logout' %}">Cerrar Sesión</a></li>
            {% else %}
            <li><a href="{% url 'registration_register' %}">Registrarse</a></li>
            {% endif %}
          </ul>

          {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
            <form class='navbar-form navbar-right' method='POST' action='{% url "auth_login" %}'>{% csrf_token %}
              <div class='form-group'>
                  <input type='text' class='form-control' name='username' placeholder='Usuario' />
              </div>
              <div class='form-group'>
                  <input type='password' class='form-control' name='password' placeholder='Contraseña' />
              </div>
              <button type='submit' class='btn btn-default'>Entrar</button>
          </form>
          {% endif %}


        </div><!--/.nav-collapse -->

    </nav>

adoa/templates/queEsPatron.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
<!DOCTYPE html>



{% block head_title %}Index | {{ block.super }}{% endblock %}

{% block jumbotron %}
 
  
    <div class="container">
      <div class="jumbotron text-center">
      <div class="row">
        <div class="col-xs12"><img src="{% static 'img/index/patron2.png' %}" class="img-responsive" alt="Placeholder image"> </div>
      </div>
    </div>
  </div>
 
{% endblock %}
{% block content %}
<section>
  <div class="container well">
    <div class="row">
      <div class="col-md-4 col-sm-6 col-lg-12">
        <div class="media">
      <!--   <div class="media-left"> <a href="#">  </a> </div>-->
          <div class="media-body">
          Los Patrones Pedagógicos formalizan el conocimiento experto de la enseñanza y el aprendizaje, fácilmente comunicable a aquellos que necesitan ese conocimiento. </div>
        </div>
      </div>
</div>
  </div>
</section>
  <center> <a href="{% url 'adoa:index' %}"> <button type="button" class="btn btn-default">Volver</button></a></center>
  <br></br>
    <br></br>
      <br></br>
	  {% endblock %}