adoa/adoa/urls.py
from django.conf.urls import *
from adoa.views import *
from django.conf.urls import include, url
	


urlpatterns = [

    url(r'^$', index),
    url(r'^index/', index, name='index'),
    url(r'^ayuda/', ayuda, name='ayuda'),
    url(r'^queEsOA/', queEsOA, name='queEsOA'),
    url(r'^queEsPatron/', queEsPatron, name='queEsPatron'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^inicioOA/', inicioOA, name = 'inicioOA'),
    url(r'^contenidosOA/', contenidosOA, name = 'contenidosOA'),
    url(r'^guardarcontenidosOA/', guardarcontenidosOA, name = 'guardarcontenidosOA'),
    url(r'^guardarActividadesOA/', guardarActividadesOA, name = 'guardarActividadesOA'),    
    url(r'^patrones/', patrones, name = 'patrones'),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),



]

adoa/urls.py
from django.conf.urls import include, url
from adoa.views import *

# from . import views

urlpatterns = [
    # url(r'^$', index, name='index'),
    url(r'^$', Index.as_view()),
    url(r'^index/', Index.as_view(), name='index'),


    url(r'^queEsOA/', QueEsOA.as_view(), name='queEsOA'),
    url(r'^queEsPatron/', QueEsPatron.as_view(), name='queEsPatron'),
    url(r'^ayuda/', Ayuda.as_view(), name='ayuda'),
    url(r'^patrones/', PatronesView.as_view(), name = 'patrones'),

    url(r'^oa/$', ObjetoAprendizajeList.as_view(), name='list'),
    url(r'^oa/(?P<pk>\d+)$', ObjetoAprendizajeDetail.as_view(), name='detail'),
    url(r'^oa/nuevo$', ObjetoAprendizajeCreate.as_view(), name='new'),
    url(r'^oa/editar/(?P<pk>\d+)$', ObjetoAprendizajeUpdate.as_view(), name='edit'),
    url(r'^oa/borrar/(?P<pk>\d+)$', ObjetoAprendizajeDelete.as_view(), name='delete'),
    url(r'^oa/patron$', ContenidoView.as_view(), name='patron'),
    url(r'^oa/contenido$', ContenidoCreate.as_view(), name='contenido'),
    url(r'^oa/elementoasociacion$', ElementoAsociacionCreate.as_view(), name='elementoasociacion'),
    url(r'^oa/elementovof$', ElementoVoFCreate.as_view(), name='elementovof'),
    url(r'^oa/elementoidentificacion$', ElementoIdentificacionCreate.as_view(), name='elementoidentificacion'),
    url(r'^oa/elementoordenamiento$', ElementoOrdenamientoCreate.as_view(), name='elementoordenamiento'),
    url(r'^oa/elementoopcionmultiple$', ElementoOpcionMultipleCreate.as_view(), name='elementoopcionmultiple'),
]

proyecto/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^', include('adoa.urls', namespace='adoa')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

adoa/adoa/models.py
from django.db import models
from django.contrib import admin
# from tinymce.models import HTMLField
from django.contrib.auth.models import *
from ckeditor.fields import RichTextField
# Create your models here.



class Patron(models.Model):
    titulo = models.CharField(max_length=30)
    descripcion = RichTextField()
    problemas = RichTextField()
    solucion = RichTextField()
    def __unicode__(self):
       return self.titulo


class ContenidoPatron(models.Model):
    orden = models.IntegerField()
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length = 200)
    patron = models.ForeignKey(Patron)
    def _get_titulo(self):
        return self.titulo
    def _get_descripcion(self):
        return self.descripcion
    def _get_orden(self):
        return self.orden

    def __unicode__(self):
       return self.titulo


class ObjetoAprendizaje(models.Model):
    titulo=models.CharField(max_length=30)
    descripcion= RichTextField()
    patron = models.ForeignKey(Patron)
    user = models.ForeignKey(User)
    def setearContenidos(self):
        li=[]
        for contenidoPatron in ContenidoPatron.objects.all():
            if contenidoPatron.patron == self.patron:
                contenido = Contenido(titulo = contenidoPatron._get_titulo(), descripcion = contenidoPatron._get_descripcion(), orden = contenidoPatron._get_orden(),objetoAprendizaje = self)
                li.append(contenido)
        return li
    def setearActividad(self):
        li=[]
        vof=VerdaderoFalso(titulo = "VerdaderoFalso", descripcion = "aoifjoiajs", enunGeneral = "oiafsoij", objetoAprendizaje= self)
        li.append(vof)
        return li
    def __unicode__(self):
       return self.titulo


class Contenido(models.Model):
    orden = models.IntegerField()
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length = 200)
    contenido = RichTextField()
    objetoAprendizaje = models.ForeignKey(ObjetoAprendizaje)
    def __unicode__(self):
       return self.titulo

#--------------------------------------------------------------------------

class Actividad(models.Model):
    titulo = models.CharField(max_length=30)
    objetoAprendizaje = models.ForeignKey(ObjetoAprendizaje)
    def __unicode__(self):
       return self.titulo

#--------------------------------------------------------------------------

class VerdaderoFalso(Actividad):
    enunGeneral =  models.CharField(max_length = 30)
    descripcion = RichTextField()


class ElementoVoF(models.Model):
    enunciado = models.CharField(max_length = 30)
    verdad = models.BooleanField()
    VoF = models.ForeignKey(VerdaderoFalso)

#--------------------------------------------------------------------------

class Ordenamiento(Actividad):
    enunGeneral =  models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoOrdenamiento(models.Model):
    enunciado = models.CharField(max_length = 30)
    orden = models.IntegerField()
    ordenamiento = models.ForeignKey(Ordenamiento)

#--------------------------------------------------------------------------


class OpcionMultiple(Actividad):
    enunGeneral = models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoOpcionMultiple(models.Model):
    enunciado = models.CharField(max_length = 30)
    correcta = models.CharField(max_length = 30)
    incorrecta1 = models.CharField(max_length = 30)
    incorrecta2 = models.CharField(max_length = 30)
    incorrecta3 = models.CharField(max_length = 30)
    multiple = models.ForeignKey(OpcionMultiple)

#-------------------------------------------------------------

class Identificacion(Actividad):
    enunGeneral = models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoIdentificacion(models.Model):
    enunciado = models.CharField(max_length = 30)
    correcto = models.BooleanField()
    identificacion = models.ForeignKey(Identificacion)

#----------------------------------------------------------

class Asociacion(Actividad):
    enunGeneral = models.CharField(max_length = 30)
    descripcion = RichTextField()

class ElementoAsosiacion(models.Model):
    enunciado = models.CharField(max_length = 30)
    imagen = models.ImageField()
    asociacion = models.ForeignKey(Asociacion)

adoa/forms.py
from django import forms
from django.forms import ModelForm, inlineformset_factory, BaseInlineFormSet, formset_factory
from django.forms.formsets import BaseFormSet
from models import *
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from ckeditor.widgets import CKEditorWidget
from crispy_forms.bootstrap import *
from djangoformsetjs.utils import formset_media_js
import pdb

class ObjetoAprendizajeForm(forms.ModelForm):
    class Meta:
        model = ObjetoAprendizaje
        fields = ['titulo','patron','descripcion']
    titulo = forms.CharField(max_length = 30)
    descripcion = forms.CharField(widget=CKEditorWidget())
    patron = forms.ModelChoiceField(queryset=Patron.objects.all())
    def __init__(self, *args, **kwargs):
        super(ObjetoAprendizajeForm, self).__init__(*args, **kwargs)
        self.helper= FormHelper()
        self.helper.layout = Layout(
            Div(
                Field('patron'),
                HTML("<a href= '{% url 'adoa:patrones' %}''>Que patron elegir? </a>"),
                Field('titulo'),
                Field('descripcion'),
                # HTML('<input type="submit" class="btn btn-primary" value="Continuar &rarr;">'),
        css_class='row-fluid'),
        )
#--------------------------------------------------------------------------
class PatronForm(ModelForm):
    class Meta:
        model = Patron
        fields = ['titulo', 'descripcion', 'problemas', 'solucion']
# #--------------------------------------------------------------------------
class ContenidoForm(forms.ModelForm):
    class Meta:
        model = Contenido
        fields = ['orden','titulo','descripcion','contenido']
    orden = forms.IntegerField()
    titulo = forms.CharField(max_length=100)
    descripcion = forms.CharField(max_length=300)
    contenido = forms.CharField(widget=CKEditorWidget())
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Field('orden',type='hidden'),
                Field('titulo'),
                Field('descripcion'),
                Field('contenido'),
                css_class='row-fluid'),
            )
        super(ContenidoForm, self).__init__(*args, **kwargs)
#--------------------------------------------------------------------------

class ElementoVoFForm(forms.ModelForm):
    class Meta:
        model = ElementoVoF
        fields = ['enunciado','verdad']

class ElementoAsociacionForm(forms.ModelForm):
    class Meta:
        model = ElementoAsociacion
        fields = ['enunciado','imagen']

class ElementoIdentificacionForm(forms.ModelForm):
    class Meta:
        model = ElementoIdentificacion
        fields = ['enunciado','correcto']

class ElementoOpcionMultipleForm(forms.ModelForm):
    class Meta:
        model = ElementoOpcionMultiple
        fields = ['enunciado','correcta','incorrecta1','incorrecta2','incorrecta3']

class ElementoOrdenamientoForm(forms.ModelForm):
    class Meta:
        model = ElementoOrdenamiento
        fields = ['enunciado','orden']
#--------------------------------------------------------------------------

class UserLoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

#--------------------------------------------------------------------------

adoa/adoa/views.py
from django.template import loader, Context
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from adoa.models import *
from django.shortcuts import render_to_response
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from forms import *
from django.contrib.sessions import *
from django.contrib.admin import *
from django.forms import formsets
from django.forms import modelformset_factory
from django.forms import formset_factory






# Create your views here.
def archive(request):
    patrones = Patron.objects.all()
    mi_template = loader.get_template("archive.html")
    mi_contexto = Context({'patrones': patrones})
    return HttpResponse(mi_template.render(mi_contexto))


def ayuda(request):
    title = 'Sign Up Now'
    context = {
        "title": title,
     }
    return render (request,"ayuda.html",context)


def queEsOA(request):
    title = 'Sign Up Now'
    context = {
        "title": title,
     }
    return render (request,"queEsOA.html",context)
    


def queEsPatron(request):
    title = 'Sign Up Now'
    context = {
        "title": title,
     }
    return render (request,"queEsPatron.html",context)



def index(request):
    title = 'Sign Up Now'
    form = UserLoginForm(request.POST or None)
    context = {
        "title": title,
        "form": form
    }
    if form.is_valid():
        instance = form.save(commit=False)
        username = form.cleaned_data.get("username")
        if not username:
            username = "New username"
        instance.username = username
        # if not instance.full_name:
        #    instance.full_name = "Justin"
        instance.save()
        context = {
            "title": "Thank you"
        }
    # if request.user.is_authenticated() and request.user.is_staff:
    #     queryset = User.objects.all()
    #     context = {
    #         "queryset": queryset
    #     }
    return render(request, "index.html", context)


def inicioOA(request):
    title = 'Inicio OA'
    form = ObjetoAprendizajeForm(request.POST or None)
    context = {
        "title": title,
        "form": form
    }


    if form.is_valid():
       
        titulo1 = form.cleaned_data.get("titulo")
        descripcion1 = form.cleaned_data.get("descripcion")
        patron1 = form.cleaned_data.get("patron")
        user_request = request.user 
        

        user = User.objects.get(username = user_request)
        oa = ObjetoAprendizaje(titulo = titulo1, descripcion = descripcion1, patron = patron1, user = user)
        
        if not ObjetoAprendizaje.objects.filter(pk=oa.pk).exists():
            oa.save()
            for contenido in oa.setearContenidos():
                contenido.save()
            for vof in oa.setearActividad():
                print vof
                vof.save()
        request.session["oa_pk"] = oa.pk

        context = {
            "title": "Thank you",
             "oa": oa
        }

        return contenidosOA(request)
    else:
        return render(request, "inicioOA.html", context)
    
def contenidosOA(request):
    
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])
    title = 'Contenidos OA'
    ContenidoFormSet =  inlineformset_factory(ObjetoAprendizaje,Contenido,fields=('orden','titulo','descripcion','contenido','objetoAprendizaje'), extra = 0)
    context = { 
            "title": title,
        }

    formset = ContenidoFormSet(instance = oa,)
    context = { 
        "title": title,
        "formset": formset,
    }
    return render(request,"contenidosOA.html", context)


def guardarcontenidosOA(request):
    ContenidoFormSet =  inlineformset_factory(ObjetoAprendizaje,Contenido,fields=('orden','titulo','descripcion','contenido','objetoAprendizaje'), extra = 0)
    
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])
        
    formset = ContenidoFormSet(request.POST, instance = oa)

    title = 'Guardar contenidos OA'
    context = { 
            "title": title,
        }
    for form in formset:
        print form.as_p

    print "1111"
    print formset.errors
    
    if formset.is_valid():
        print "22222"
        for f_form in formset:
            if f_form.is_valid():
                print "3333"
                orden =  f_form.cleaned_data.get("orden")
                titulo = f_form.cleaned_data.get("titulo")
                descripcion = f_form.cleaned_data.get("descripcion")
                content = f_form.cleaned_data.get("contenido")
                objetoAprendizaje = f_form.cleaned_data.get("objetoAprendizaje")
                contenido = Contenido(orden = orden, titulo = titulo, descripcion = descripcion,contenido = content, objetoAprendizaje = objetoAprendizaje)
                contenido.save()
                print "4444"
            return actividades(request)
    else:
        return ayuda(request)



def patrones(request):
    title = 'Patrones'
    patrones = Patron.objects.all()
    form = PatronForm()
    context = {
        "title":title,
        "form": form,
        "patrones": patrones
    }
    return render(request,"patrones.html",context)

def actividades(request):
    title = 'actividades'
    ActividadFormset = inlineformset_factory(ObjetoAprendizaje,VerdaderoFalso,fields=('titulo','enunGeneral','descripcion','objetoAprendizaje'), extra = 0)
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])
    formset = ActividadFormset(instance = oa)

    context = { 
        "title": title,
        "formset": formset,
    }
    return render(request,"actividades.html", context)


def guardarActividadesOA(request):
    ActividadFormset = inlineformset_factory(ObjetoAprendizaje,VerdaderoFalso,fields=('titulo','enunGeneral','descripcion','objetoAprendizaje'), extra = 0)
    
    oa = ObjetoAprendizaje.objects.get(pk=request.session["oa_pk"])        
    formset = ActividadFormSet(request.POST, instance = oa)

    title = 'Guardar Actividades OA'
    context = { 
            "title": title,
        }
    for form in formset:
        print form.as_p

    print "1111"
    print formset.errors
    
    if formset.is_valid():
        print "22222"
        for f_form in formset:
            if f_form.is_valid():
                print "3333"
                titulo = f_form.cleaned_data.get("titulo")
                descripcion = f_form.cleaned_data.get("descripcion")
                enunGeneral = f_form.cleaned_data.get("enunGeneral")
                objetoAprendizaje = f_form.cleaned_data.get("objetoAprendizaje")
                contenido = Contenido(titulo = titulo, descripcion = descripcion, enunGeneral = enunGeneral, objetoAprendizaje = objetoAprendizaje)
                contenido.save()
        return index(request)
    else:
        return ayuda(request)

adoa/templates/adoa/actividad_form.html
{% load crispy_forms_tags %}
{%  for form in formset %}
<div class=actividad-form>
  {% crispy form %}
  <a onclick="deleteThis(this)" class=delete-actividad href="javascript:void(0)">Quitar</a>
</div>
{% endfor %}

adoa/templates/adoa/contenido_form.html
{% load crispy_forms_tags %}
{%  for form in formset %}
<div class=contenido-form>
  {% crispy form %}
  <a onclick="deleteThis(this)" class=delete-contenido href="javascript:void(0)">Quitar</a>
</div>
{% endfor %}

adoa/templates/adoa/elementoasociacion_form.html
{% load crispy_forms_tags %}
{%  for form in formset %}
<div class=elementoasosiacion-form>
  {% crispy form %}
  <a onclick="deleteThis(this)" class=delete-elementoasosiacion href="javascript:void(0)">Quitar</a>
</div>
{% endfor %}

adoa/templates/adoa/elementoidentificacion_form.html
{% load crispy_forms_tags %}
{%  for form in formset %}
<div class=elementoidentificacion-form>
  {% crispy form %}
  <a onclick="deleteThis(this)" class=delete-elementoidentificacion href="javascript:void(0)">Quitar</a>
</div>
{% endfor %}

adoa/templates/adoa/elementoopcionmultiple_form.html
{% load crispy_forms_tags %}
{%  for form in formset %}
<div class=elementoopcionmultiple-form>
  {% crispy form %}
  <a onclick="deleteThis(this)" class=delete-elementoopcionmultiple href="javascript:void(0)">Quitar</a>
</div>
{% endfor %}

adoa/templates/adoa/elementoordenamiento_form.html
{% load crispy_forms_tags %}
{%  for form in formset %}
<div class=elementoordenamiento-form>
  {% crispy form %}
  <a onclick="deleteThis(this)" class=delete-elementoordenamiento href="javascript:void(0)">Quitar</a>
</div>
{% endfor %}

adoa/templates/adoa/objeto_and_contenidos.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load get_name %}
{% load staticfiles %}
{% load debug_tags %}
{% block scripts %}
  <script type="text/javascript" src="{% static 'js/objeto_aprendizaje.js' %}"></script>
{% endblock %}
{% block content %}
<h1>Objeto y contenidos</h1>
<form action="{% url 'adoa:new'%}" method="post">
{% csrf_token %}

{{ form.titulo|as_crispy_field }}
{{ form.patron|as_crispy_field }}
<br>
<a href="{% url 'adoa:patrones' %}">Que patron elegir? </a>
{{ form.descripcion|as_crispy_field }}

{% for formset in inlines %}
  {% with formset.model|to_class_name|lower as model_name %}
    {% if forloop.first %}
      <h2>{{ model_name|title }}s</h2>
    {% endif %}
    <input class={{model_name}}-amount type=number value={{formset|length}} hidden>
    <div class={{model_name}}-formset>
      {{formset|crispy}}
    </div>
    {% if forloop.first %}
      <a class=add-contenido href="javascript:void(0)">Agregar</a>
      <h2>Actividades</h2>
    {% endif %}
  {% endwith %}
{% endfor %}
<h3>Agregar actividades</h3>

<select class=select-actividad>
  <option value="">-------</option>
  <option value="vof">Verdadero o Falso</option>
  <option value="opcion_multiple">Opcion Multiple</option>
  <option value="asociacion">Asociacion</option>
  <option value="identificacion">Identificacion</option>
  <option value="ordenamiento">Ordenamiento</option>
</select>
<p class=no-patron href="javascript:void(0)">Por favor, seleccione un patron para continuar.</p>
<input class=send-form type="submit" value="Submit" />
</form>
{% endblock %}

adoa/templates/adoa/objeto_and_contenidos0.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load get_name %}
{% load staticfiles %}
{% load debug_tags %}
{% block scripts %}
  <script type="text/javascript" src="{% static 'js/objeto_aprendizaje.js' %}"></script>
{% endblock %}
{% block content %}
<h1>Objeto y contenidos</h1>
<form action="{% url 'adoa:new'%}" method="post">

{{ form.titulo|as_crispy_field }}
{{ form.patron|as_crispy_field }}
<br>
<a href="{% url 'adoa:patrones' %}">Que patron elegir? </a>
<br>
{{ form.descripcion|as_crispy_field }}


{% for formset in inlines %}
{% csrf_token %}
  {% with formset.model|to_class_name|lower as model_name %}
  <input class={{model_name}}-amount type=number value={{formset|length}} hidden>
    <h1>{{ model_name|title }}{% if model_name == 'actividad' %}e{% endif %}s</h1>
    <div class={{model_name}}-formset>
      {{formset}}
    </div>
    {% if model_name == 'contenido' %}
    <a class=add-contenido href="javascript:void(0)">Agregar</a>
    {% endif %}
    {% if model_name == 'actividad' %}
    <a class=add-actividad href="javascript:void(0)">Agregar</a>
    <div class=actividad-template></div>
    {% endif %}
  {% endwith %}
{% endfor %}
<p class=no-patron href="javascript:void(0)">Por favor, seleccione un patron para continuar.</p>
<input class=send-form type="submit" value="Submit" />
</form>
{% endblock %}

adoa/templates/adoa/objeto_and_contenidos1.html
<!DOCTYPE html>
<html>
<head>
        <title>Order and Items</title>
</head>
<body>

<h1>Order and Items</h1>
<form action="{% url 'adoa:new'%}" method="post">
{% csrf_token %}
{{ form }}

{% for formset in inlines %}

{{ formset }}

{% endfor %}


<input type="submit" value="Submit" />

</form>

</body>
</html>

adoa/templates/adoa/objetoaprendizaje_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

adoa/templates/adoa/objetoaprendizaje_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<h1>{{ objetoaprendizaje.titulo | safe }}</h1>
<p>Patron: <i>{{ objetoaprendizaje.patron }}</i></p>
<p>Descripcion: {{ objetoaprendizaje.descripcion| safe }}</p>
<p>
    <a href="{% url "adoa:list" %}">Regresar</a>
</p>
{% endblock %}

adoa/templates/adoa/objetoaprendizaje_form.html
{% extends "base.html" %} {% load i18n %} {% load crispy_forms_tags %} {% block content %}
<form method="post" enctype="multipart/form-data" action={% url 'adoa:new' %}>
  {% csrf_token %}
  <div class="row">
    {% crispy form %}
  </div>
</form>
{% endblock %}

adoa/templates/adoa/objetoaprendizaje_form1.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block content %}
<form id="father-form" method="POST" enctype="multipart/form-data" action=".">
{% csrf_token %}
<div class="row">
  {% for f in form %}
    <div class="span3">{{ f.label }}<br />{{ f }}
      {% if f.errors %}
          {% for v in f.errors %}
            <br /><span style="color:red;">{{ v }}</span>
          {% endfor %}
      {% endif %}
    </div>
 {% endfor %}
</div>
<hr />
<h2>Sons:</h2>
<table class="table-striped">
 <table>
 {%  for f2 in inlines %}
   <tr id="{{ f2.prefix }}-row">
      {% for i in f2 %}
        <td>
           {{ i }}{% if i.errors %}<span style="color:red;">{{ i.errors }}</span>{% endif %}
        </td>
      {% endfor %}
   </tr>
 {% endfor %}
</table>
{{ inlines.management_form }}
<input type="submit" class="btn btn-primary" value="Go Go Gadget &rarr;">
</form>
<script type="text/javascript">
    $(function() {
        $('#father-form tr').formset();
    })
</script>
{% endblock %}

adoa/templates/adoa/objetoaprendizaje_list.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Objetos de aprendizaje</h1>

<p>
    <a href="{% url "adoa:new" %}">Agregar oa</a>
</p>

<ul>
    {% for objetoaprendizaje in object_list %}
        <li>
            <p>{{ objetoaprendizaje.titulo | safe}}</p>
            <p>
              <a href="{% url "adoa:detail" objetoaprendizaje.id %}">Ver</a> |
              <a href="{% url "adoa:edit" objetoaprendizaje.id %}">Editar</a> |
              <a href="{% url "adoa:delete" objetoaprendizaje.id %}">Borrar</a>
            </p>
        </li>
    {% endfor %}
</ul>
{% endblock %}